# muss man hier definieren, sonst klappt das nicht für beide includes
stages:
  - deploy-int
  - deploy-prod

include:
  # use template for gitlab pipeline to deploy to shinyapps.io
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "main"
    file: "deploy-to-shinyapps.yml"
  # use template for gitlab pipeline to push main to github 
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "main"
    file: "publish-to-github.yml"

shiny-deploy-int:
  extends:
    - .shiny-deploy-int

shiny-deploy-prod:
  extends:
    - .shiny-deploy-prod

publish-to-github-orphan-remove-fonts:
  extends:
    - .publish-to-github-orphan-remove-fonts